### ISSUE TITLE
Error Halt add-on with exit code 1

### ISSUE THREAD

**Issue by krzakx** [allenporter/stream-addons#90] opened 2022-12-30 16:12 UTC
Hello to you all.
I do face following issue:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-rtsp-to-web
[17:02:01] INFO: Creating configuration
cont-init: info: /etc/cont-init.d/01-rtsp-to-web exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun rtsp-to-web (no readiness notification)
s6-rc: info: service legacy-services successfully started
[17:02:04] INFO: Starting discovery service
[17:02:04] INFO: Starting RSTPtoWeb
[16:02:05] WARNING: Halt add-on with exit code 1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

Addon installation is done on Raspberry Pi 3 HAOS
```
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest
```

Here some system logs
```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:124
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: December 29, 2022 at 12:40:34 PM (6 occurrences)
Last logged: 5:09:38 PM

Failed to to call /addons/3d360630_rtsp-to-webrtc/install - Can't install ghcr.io/allenporter/armv7-rtsp-to-webrtc:1.0.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=1.0.1&fromImage=ghcr.io%2Fallenporter%2Farmv7-rtsp-to-webrtc&platform=linux%2Farm%2Fv7: Internal Server Error ("Head "https://ghcr.io/v2/allenporter/armv7-rtsp-to-webrtc/manifests/1.0.1": dial tcp 140.82.121.34:443: i/o timeout")
Failed to to call /addons/3d360630_rtsp-to-webrtc/stats - Container addon_3d360630_rtsp-to-webrtc is not running
Failed to to call /addons/3d360630_rtsp-to-web/stats - Container addon_3d360630_rtsp-to-web is not running
```

Even restarting whole host device doesn't help, any idea?

**Comment by krzakx** [comment] 2022-12-30 16:16
just a loose thought came and I figure out something....
well, after port change from default one from **8083** to **1234** it workout! 
What does it mean for me? Some diffrent addon/service is using 8083?

**Comment by allenporter** [comment] 2022-12-30 16:23
This is discussed in #61 though i'm unable to reproduce and am unsure about the root cause or how it's even possible.

**Comment by allenporter** [comment] 2022-12-30 17:54
Marking as duplicate of  #61 -- welcome your participation there if you learn anything.

**Closed by allenporter** 2022-12-30 17:54 UTC
