### ISSUE TITLE
Nest Doorbell and RTSPtoWeb - WebRTC on dashboards Quality and Reliability Issues since around 2022.7

### ISSUE THREAD

**Issue by kpurintun** [allenporter/stream-addons#75] opened 2022-07-13 13:50 UTC
Since 2022.7 came out..  or around that time.  I noticed that the video on my dashboards has not been working right.  

If I set the card to 'live', the video will be all kinds of aliased and ghosted and the video will simply freeze after a while. The ghosting effect has a significant growing distortion that will 'pop' back to a refreshed image every few seconds. 

If I set the card to 'auto' it will work for a random amount of time before simply doesn't work for another random amount of time and shows an [ X ] type icon..  My video does work to some extent, and my thermostats still work as expected.   

I have some Unifi Protect Cams and they are working as that have been.  The older G3 Domes and Bullets do not work well with RTSPtoWeb - WebRTC which I believe has something to do with the way the domes and bullets do rstps.   the G4 dome and g3 instant work as expected.  No weird video distortions.

Is this something that anyone else has experience? or might now any solutions?

Currently running Home Assistant OS 8.2 and 2022.7.2 on a VM in Unraid, MariaDB, latest RTSPtoWeb - WebRTC, access to Home Assistant via nginx, nest doorbell is the original, unifi cams are g3 dome, g3 bullet, g4 dome, and g3 instant connected to the udmp.

I have always had some errors related to the nest that look like:

Logger: homeassistant.components.stream.stream.camera.front_door
Source: components/stream/__init__.py:416
Integration: Stream ([documentation](https://www.home-assistant.io/integrations/stream), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+stream%22))
First occurred: July 9, 2022 at 11:01:01 PM (577 occurrences)
Last logged: 9:25:49 AM

Error from stream worker: Error opening stream (EXIT, Immediate exit requested) rtsps://stream-ue1-delta.dropcam.com:443/sdm_live_stream/CiU*****?auth=****
Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsps://stream-ue1-delta.dropcam.com:443/sdm_live_stream/CiU******Y0w?auth=****
Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsps://stream-ue1-delta.dropcam.com:443/sdm_live_stream/CiU******ZW0A?auth=****
Error from stream worker: Error opening stream (HTTP_FORBIDDEN, Server returned 403 Forbidden (access denied)) rtsps://stream-ue1-delta.dropcam.com:443/sdm_live_stream/CiU*****aY0w?auth=****
Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsps://stream-ue1-delta.dropcam.com:443/sdm_live_stream/CiUA*****HQ?auth=****

**Comment by allenporter** [comment] 2022-07-17 00:28
Regarding the last message, if you're seeing 404 not found errors, that is a Nest server side stream issue https://github.com/home-assistant/core/issues/60353 and home assistant and RTSPtoWeb can't do anything about it.

**Comment by kpurintun** [comment] 2022-07-17 14:18
> Regarding the last message, if you're seeing 404 not found errors, that is a Nest server side stream issue [home-assistant/core#60353](https://github.com/home-assistant/core/issues/60353) and home assistant and RTSPtoWeb can't do anything about it.

I am seeing that too..  where the webrtc stream distorts until it freezes..  if i set the card to ‘auto’ then it updates the picture for a while, then stops and i get that 404 looking broken link page..  then it comes back for a couple hours..  

On thing that may be interesting is that i set up this integration the old way and not the new UI way.. does that make a difference?  I just tried to reload the integration.  May have to start over and reinstall the integration using the new method..  could I maybe be hitting the API too much?  Does the api for tstats also impact the cameras?  Or are they separate counters?

**Comment by kpurintun** [comment] 2022-07-17 14:21
Oh..  i also have two ‘tablet dashboards’ that show this cam constantly..  it hasn’t been a problem until recently

**Comment by allenporter** [comment] 2022-07-17 15:42
RTSPtoWeb doesn't really care much about the home assistant version or how its setup. It's only getting an RTSP url from home assistant to nests servers.

Another way to say this is you are running a version of RTSPtoWeb that has not changed at all in months. I worry something changed on the server side or something else related to the cloud camera degraded.  You may want to disable RTSPtoWeb integration and config things work well in home assistant with HLS.

I think in order to fix something like this you have to capture contents of the stream somehow and work with the RTSPtoWeb author. (I don't know how to do this.)

**Comment by allenporter** [comment] 2022-11-14 15:22
Closing since this is a duplicate of https://github.com/home-assistant/core/issues/60353

**Closed by allenporter** 2022-11-14 15:22 UTC
