### ISSUE TITLE
RTSPWeb remote access via https

### ISSUE THREAD

**Issue by Papadoma** [allenporter/stream-addons#66] opened 2022-05-03 23:00 UTC
I think I might be missing something but how am I supposed to configure remote access via https? I have local access on port 8083. Surely I don't have to forward this port, that would give unlimited access to all my feeds. 

With the custom WebRTC component, a range of ports could be forwarded and it would work.

**Comment by allenporter** [comment] 2022-05-04 03:44
Duplicate of https://github.com/allenporter/stream-addons/issues/62

**Comment by allenporter** [comment] 2022-05-04 12:49
Hi, if you're asking about remote access in general the other issue is talking about how to do it. You are asking here for a particular solution forwarding the port of the add-on server, which isn't the way to do remote access.  The other bug is tracking the solution (isn't complete yet)

**Comment by allenporter** [comment] 2022-05-04 12:51
(The webrtc stream does not use that port)

**Comment by Papadoma** [comment] 2022-05-04 13:34
> Hi, if you're asking about remote access in general the other issue is talking about how to do it. You are asking here for a particular solution forwarding the port of the add-on server, which isn't the way to do remote access. The other bug is tracking the solution (isn't complete yet)

I was thinking the latter, more in line of asking for the way that this addon is supposed to allow HASS users (both hassio and supervised) to allow access to their camera feeds via the frontend

Without diving into it much, I see no straightforward way of setting this up. I have a notion about the solution suggested in #62  but I don't see it applicable to the addon, more like a behind the scenes situation. 

I do keep the last part that its a work in progress though.

**Closed** 2022-05-27 05:31 UTC
